[
{ "tag": "function", "name": "arc", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:98:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "bezier", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:99:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "bSpline", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:100:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "NUBS", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:101:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "hermite", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:102:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "catmullRom", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:103:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "circle", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:105:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "ellipse", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:106:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "function", "name": "polyBezier", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:107:7", "variadic": false, "inline": false, "storage-class": "none", "parameters": [], "return-type": { "tag": ":int", "bit-size": 32, "bit-alignment": 32 } },
{ "tag": "const", "name": "M_PI", "ns": 0, "location": "/home/dk/lisp/hu.dwim.sdl/c2ffi-spec/SDL2_wip.h:38:9", "type": { "tag": ":double", "bit-size": 64, "bit-alignment": 64 }, "value": 3.141593e+00 }
]
